seed: 4
target_sr: 16000

batch_size: 12
test_batch_size: 16
train-test-ratio: .8
save_test_loader: true

# Whether or not to use wav2vec2 model as downstream loss.
# This will compute the CTC loss and add it to the original MSE loss:
# mse_loss + downstream_loss_factor * ctc_loss
use_downstream_loss: false
downstream_loss_factor: .01

# Whether or not to compute WER using wav2vec2 model during evaluation
compute_wer: false

# Arguments passed to transformers.Trainer class
trainer-args:
  output_dir: outputs
  num_train_epochs: 150
  bf16: True

  report_to: tensorboard
  logging_strategy: steps
  logging_steps: 10
  eval_strategy: epoch
  save_strategy: epoch
  save_total_limit: 50

  gradient_accumulation_steps: 2

  optim: adamw_8bit
  weight_decay: 1.0e-2

  learning_rate: 1.0e-3
  lr_scheduler_type: "reduce_lr_on_plateau"
  lr_scheduler_kwargs:
    patience: 5
